### ISSUE TITLE
SOSE monthly climatology

### ISSUE THREAD

**Issue by wei200** [knaughten/mitgcm_python#1]
Thanks for sharing the workflow of creating a MITgcm domain. I'm trying to use your tools to reproduce the initial condition from SOSE. Can you share the path where I can download the precomputed /data/oceans_input/raw_input_data/SOSE_monthly_climatology? Thank you!

**Comment by knaughten** [comment]
Hi Wei,

Thanks for your message. The precomputed data is stored on an internal BAS server which is not publicly available, however you can precompute your own climatology by downloading the original SOSE data (http://sose.ucsd.edu/sose_stateestimation_data_05to10.html) and then using this function: https://github.com/knaughten/mitgcm_python/blob/c4e9be8d6049d141b89142c78703b6b40d8c3842/ics_obcs.py#L31

Hope that helps!
Kaitlin


Dr Kaitlin Naughten | Ocean-Ice Modeller | British Antarctic Survey

High Cross, Madingley Road, Cambridge CB3 0ET

Email: kaight@bas.ac.uk<mailto:kaight@bas.ac.uk>

________________________________

**Comment by wei200** [comment]
Thanks a lot for sharing the function.
